export const PHASES = [
  { id: 'mid-may',    label: 'Mid-May',    emoji: '🟡', color: '#F5C518', bg: 'rgba(245,197,24,0.12)' },
  { id: 'late-june',  label: 'Late June',  emoji: '🟠', color: '#FF8C42', bg: 'rgba(255,140,66,0.12)' },
  { id: 'early-july', label: 'Early July', emoji: '🔵', color: '#4DA6FF', bg: 'rgba(77,166,255,0.12)' },
  { id: 'late-july',  label: 'Late July',  emoji: '🔴', color: '#FF4D6D', bg: 'rgba(255,77,109,0.12)' },
  { id: 'final',      label: 'Final Phase', emoji: '🎓', color: '#B57BFF', bg: 'rgba(181,123,255,0.12)' },
];

export const SUBJECT_COLORS = {
  'Entrepreneurship':    '#FF8C42',
  'Mathematical Concepts': '#4DA6FF',
  'Co-curricular':       '#50C878',
  'Security':            '#FF4D6D',
  'System Analysis':     '#B57BFF',
  'Integrated Systems':  '#F5C518',
  'Web Design':          '#00D4AA',
  'University':          '#E8E8E8',
  'General':             '#A0A0A0',
};

export const TYPE_COLORS = {
  'Assignment':   '#A0A0A0',
  'Presentation': '#FF8C42',
  'Quiz':         '#4DA6FF',
  'Test':         '#FF4D6D',
  'Submission':   '#50C878',
  'Feedback':     '#B57BFF',
  'Docket':       '#F5C518',
  'Exams':        '#FF4D6D',
};

export const EVENTS = [
  // 🟡 Mid-May
  {
    id: '1',
    phase: 'mid-may',
    date: '2026-05-15',
    title: 'Assignment Handout Day',
    subject: 'General',
    type: 'Assignment',
    note: 'Multiple subjects — collect all handouts',
  },

  // 🟠 Late June
  {
    id: '2',
    phase: 'late-june',
    date: '2026-06-20',
    title: 'Presentation',
    subject: 'Entrepreneurship',
    type: 'Presentation',
    note: '',
  },
  {
    id: '3',
    phase: 'late-june',
    date: '2026-06-24',
    title: 'Quiz (Online)',
    subject: 'Entrepreneurship',
    type: 'Quiz',
    note: 'Online quiz — check platform beforehand',
  },
  {
    id: '4',
    phase: 'late-june',
    date: '2026-06-26',
    title: 'Test 1',
    subject: 'Mathematical Concepts',
    type: 'Test',
    note: '',
  },
  {
    id: '5',
    phase: 'late-june',
    date: '2026-06-27',
    title: 'Presentation',
    subject: 'Co-curricular',
    type: 'Presentation',
    note: '',
  },
  {
    id: '6',
    phase: 'late-june',
    date: '2026-06-29',
    title: 'Final Submission',
    subject: 'Co-curricular',
    type: 'Submission',
    note: '',
  },

  // 🔵 Early July
  {
    id: '7',
    phase: 'early-july',
    date: '2026-07-02',
    title: 'Final Submission',
    subject: 'Entrepreneurship',
    type: 'Submission',
    note: '',
  },
  {
    id: '8',
    phase: 'early-july',
    date: '2026-07-06',
    title: 'Security Portfolio Submission',
    subject: 'Security',
    type: 'Submission',
    note: '',
  },
  {
    id: '9',
    phase: 'early-july',
    date: '2026-07-07',
    title: 'Presentation',
    subject: 'System Analysis',
    type: 'Presentation',
    note: '',
  },
  {
    id: '10',
    phase: 'early-july',
    date: '2026-07-08',
    title: 'Final Submission',
    subject: 'System Analysis',
    type: 'Submission',
    note: '',
  },
  {
    id: '11',
    phase: 'early-july',
    date: '2026-07-13',
    title: 'Submission',
    subject: 'Integrated Systems',
    type: 'Submission',
    note: '',
  },
  {
    id: '12',
    phase: 'early-july',
    date: '2026-07-14',
    title: 'Presentation',
    subject: 'Web Design',
    type: 'Presentation',
    note: '',
  },
  {
    id: '13',
    phase: 'early-july',
    date: '2026-07-15',
    title: 'Final Submission',
    subject: 'Web Design',
    type: 'Submission',
    note: '',
  },

  // 🔴 Late July
  {
    id: '14',
    phase: 'late-july',
    date: '2026-07-20',
    title: 'Test',
    subject: 'System Analysis',
    type: 'Test',
    note: '',
  },
  {
    id: '15',
    phase: 'late-july',
    date: '2026-07-22',
    title: 'Quiz',
    subject: 'Web Design',
    type: 'Quiz',
    note: '',
  },
  {
    id: '16',
    phase: 'late-july',
    date: '2026-07-24',
    title: 'Test 2',
    subject: 'Mathematical Concepts',
    type: 'Test',
    note: '',
  },
  {
    id: '17',
    phase: 'late-july',
    date: '2026-07-27',
    title: 'Final Submission + Portfolio 2',
    subject: 'Security',
    type: 'Submission',
    note: '',
  },
  {
    id: '18',
    phase: 'late-july',
    date: '2026-07-30',
    title: 'End Semester Feedback',
    subject: 'General',
    type: 'Feedback',
    note: '',
  },
  {
    id: '19',
    phase: 'late-july',
    date: '2026-07-31',
    title: 'Last Date for Exam Docket',
    subject: 'University',
    type: 'Docket',
    note: '⚠️ Do not miss this — required for exams',
  },

  // 🎓 Final Phase
  {
    id: '20',
    phase: 'final',
    date: '2026-08-03',
    title: 'University Exams Begin',
    subject: 'University',
    type: 'Exams',
    note: '🎓 Final exams — study hard!',
  },
];
